# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_auto_20170617_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read',
            field=models.ManyToManyField(related_name='read_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
