# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dialogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='dialogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue', to='dialogue.Dialogue'),
        ),
    ]
