# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0004_auto_20170609_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialogue',
            old_name='users',
            new_name='participants',
        ),
    ]
