# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uniquser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
