# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_auto_20170522_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquser',
            name='height_field',
            field=models.IntegerField(blank=True, default=128, null=True),
        ),
        migrations.AlterField(
            model_name='uniquser',
            name='width_field',
            field=models.IntegerField(blank=True, default=128, null=True),
        ),
    ]
