# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_auto_20170522_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquser',
            name='user_kind',
            field=models.CharField(choices=[('student', 'Student'), ('academic', 'Academic'), ('staff', 'Staff')], max_length=10),
        ),
    ]
