# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0004_auto_20170522_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquser',
            name='user_kind',
            field=models.CharField(choices=[('T', 'Student'), ('C', 'Academic'), ('F', 'Staff')], default='T', max_length=1),
        ),
    ]
