# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 09:13
from __future__ import unicode_literals

import customauth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20170523_1213'),
        ('customauth', '0005_auto_20170522_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquser',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='channels.Faculty'),
        ),
        migrations.AddField(
            model_name='uniquser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='channels.Group'),
        ),
        migrations.AddField(
            model_name='uniquser',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='channels.University'),
        ),
        migrations.AlterField(
            model_name='uniquser',
            name='avatar',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=customauth.models.upload_location, width_field='width_field'),
        ),
    ]
