# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupstack',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupstacks', to='channels.Faculty'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='channels.GroupStack'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='channels.University'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
