# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 05:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subscribed_groups', models.ManyToManyField(related_name='courses_we_subscribe', to='channels.Group')),
                ('subscribed_users', models.ManyToManyField(related_name='courses_i_subscribe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
