# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20170522_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='users',
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.RemoveField(
            model_name='university',
            name='users',
        ),
    ]
