# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 14:16
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20170523_1213'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='faculty',
            managers=[
                ('objects_safe', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='group',
            managers=[
                ('objects_safe', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='groupstack',
            managers=[
                ('objects_safe', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='university',
            managers=[
                ('objects_safe', django.db.models.manager.Manager()),
            ],
        ),
    ]
