# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20170524_1716'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='faculty',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='group',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='groupstack',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='university',
            managers=[
            ],
        ),
    ]
