# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_auto_20170524_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
