# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_auto_20170525_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstack',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
