# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_auto_20170525_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstack',
            name='show_title',
            field=models.CharField(blank=True, max_length=104, null=True),
        ),
    ]
