# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_groupstack_show_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstack',
            name='show_title',
            field=models.CharField(blank=True, editable=False, max_length=104, null=True),
        ),
    ]
