# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0012_auto_20170525_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='short_titles',
            field=models.CharField(default='', max_length=100),
        ),
    ]
